"""LCM type definitions
This file automatically generated by exlcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class Transaction(object):
    __slots__ = ["timestamp", "id"]

    def __init__(self):
        self.timestamp = 0
        self.id = 0

    def encode(self):
        buf = BytesIO()
        buf.write(Transaction._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.id))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Transaction._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Transaction._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Transaction()
        self.timestamp, self.id = struct.unpack(">qi", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if Transaction in parents: return 0
        tmphash = (0x45d3109d2729b1dd) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Transaction._packed_fingerprint is None:
            Transaction._packed_fingerprint = struct.pack(">Q", Transaction._get_hash_recursive([]))
        return Transaction._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

